package com.example.rustore_app_showcase.backend

import com.example.rustore_app_showcase.shared.AppInfo
import com.example.rustore_app_showcase.shared.CategoryInfo

// в разделе что нового прямоугольник подстраивался под тексат
private const val TEST_IMAGE = "http://10.0.2.2:8080/static/test_image.png"

val allApps = listOf(
    AppInfo(
        id = 1,
        title = "СберБанк Онлайн",
        shortDescription = "Финансы и платежи",
        fullDescription = "Управляйте деньгами, оплачивайте счета и делайте переводы.",
        category = "Финансы",
        rating = 4.8,
        ratingCount = 5000,
        ratingPlace = 1,
        ageRating = 6,
        developerName = "Sberbank",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE, TEST_IMAGE),
        isInstalled = false,
        size = "210 МБ",
        lastVersion = "15.1",
        lastVersionDescription = "Новый дизайн"
    ),
    AppInfo(
        id = 2,
        title = "Т-Банк",
        shortDescription = "Банк №1",
        fullDescription = "Лучший мобильный банк с кэшбэком и инвестициями.",
        category = "Финансы",
        rating = 4.9,
        ratingCount = 4200,
        ratingPlace = 2,
        ageRating = 6,
        developerName = "T-Bank",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE),
        isInstalled = false,
        size = "190 МБ",
        lastVersion = "6.12",
        lastVersionDescription = "Улучшена стабильность"
    ),
    AppInfo(
        id = 3,
        title = "ВТБ Онлайн",
        shortDescription = "Цифровой банк",
        fullDescription = "Все банковские услуги в вашем смартфоне.",
        category = "Финансы",
        rating = 4.7,
        ratingCount = 3100,
        ratingPlace = 3,
        ageRating = 6,
        developerName = "VTB",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE),
        isInstalled = false,
        size = "180 МБ",
        lastVersion = "14.0",
        lastVersionDescription = "Обновление безопасности"
    ),
    AppInfo(
        id = 4,
        title = "Яндекс Старт",
        shortDescription = "Поиск и погода",
        fullDescription = "Все, что нужно для интернета, в одном приложении.",
        category = "Инструменты",
        rating = 4.6,
        ratingCount = 8000,
        ratingPlace = 1,
        ageRating = 0,
        developerName = "Yandex",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE),
        isInstalled = false,
        size = "95 МБ",
        lastVersion = "24.1",
        lastVersionDescription = "Умный поиск"
    ),
    AppInfo(
        id = 5,
        title = "Почта Mail.ru",
        shortDescription = "Быстрая почта",
        fullDescription = "Удобный почтовый клиент для всех ваших ящиков.",
        category = "Инструменты",
        rating = 4.5,
        ratingCount = 6500,
        ratingPlace = 2,
        ageRating = 0,
        developerName = "VK",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE),
        isInstalled = false,
        size = "70 МБ",
        lastVersion = "12.5",
        lastVersionDescription = "Тёмная тема"
    ),
    AppInfo(
        id = 6,
        title = "Госуслуги",
        shortDescription = "Гос. сервисы",
        fullDescription = "Запись к врачу, штрафы и документы в одном месте.",
        category = "Государственные",
        rating = 4.6,
        ratingCount = 9000,
        ratingPlace = 1,
        ageRating = 0,
        developerName = "Минцифры РФ",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE),
        isInstalled = false,
        size = "88 МБ",
        lastVersion = "5.0",
        lastVersionDescription = "Новые уведомления"
    ),
    AppInfo(
        id = 7,
        title = "Мой налог",
        shortDescription = "Для самозанятых",
        fullDescription = "Официальное приложение ФНС России.",
        category = "Государственные",
        rating = 4.8,
        ratingCount = 2000,
        ratingPlace = 2,
        ageRating = 0,
        developerName = "ФНС России",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE),
        isInstalled = false,
        size = "45 МБ",
        lastVersion = "2.3",
        lastVersionDescription = "Чеки по QR"
    ),
    AppInfo(
        id = 8,
        title = "Яндекс Go",
        shortDescription = "Такси и еда",
        fullDescription = "Быстрый заказ такси и доставка продуктов.",
        category = "Транспорт",
        rating = 4.9,
        ratingCount = 15000,
        ratingPlace = 1,
        ageRating = 4,
        developerName = "Yandex",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE),
        isInstalled = false,
        size = "115 МБ",
        lastVersion = "4.90",
        lastVersionDescription = "Улучшена навигация"
    ),
    AppInfo(
        id = 9,
        title = "2ГИС",
        shortDescription = "Карты и справочник",
        fullDescription = "Подробные карты городов даже без интернета.",
        category = "Транспорт",
        rating = 4.8,
        ratingCount = 12000,
        ratingPlace = 2,
        ageRating = 4,
        developerName = "2GIS",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE),
        isInstalled = false,
        size = "155 МБ",
        lastVersion = "11.2",
        lastVersionDescription = "Схемы этажей"
    ),
    AppInfo(
        id = 10,
        title = "Яндекс Карты",
        shortDescription = "Навигатор",
        fullDescription = "Транспорт онлайн и лучшие маршруты.",
        category = "Транспорт",
        rating = 4.8,
        ratingCount = 14000,
        ratingPlace = 3,
        ageRating = 4,
        developerName = "Yandex",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE),
        isInstalled = false,
        size = "140 МБ",
        lastVersion = "12.0",
        lastVersionDescription = "3D-здания"
    ),
    AppInfo(
        id = 11,
        title = "Мир Танков",
        shortDescription = "Легендарные бои",
        fullDescription = "Масштабные танковые сражения онлайн.",
        category = "Игры",
        rating = 4.5,
        ratingCount = 50000,
        ratingPlace = 1,
        ageRating = 12,
        developerName = "Lesta Games",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE),
        isInstalled = false,
        size = "2.5 ГБ",
        lastVersion = "1.24",
        lastVersionDescription = "Новый сезон"
    ),
    AppInfo(
        id = 12,
        title = "Rush Royale",
        shortDescription = "Tower Defense",
        fullDescription = "Сражайся в PvP и защищай свой замок.",
        category = "Игры",
        rating = 4.6,
        ratingCount = 30000,
        ratingPlace = 2,
        ageRating = 12,
        developerName = "MY.GAMES",
        iconUrl = TEST_IMAGE,
        screenshots = listOf(TEST_IMAGE),
        isInstalled = false,
        size = "600 МБ",
        lastVersion = "23.0",
        lastVersionDescription = "Новые герои"
    )
)

val allCategories = listOf(
    CategoryInfo(
        id = 1,
        title = "Финансы",
        appsCount = 0,
        icon = 0,
        color = "0xFFD1F6D3",
        description = "Полный контроль ваших финансов"
    ),
    CategoryInfo(
        id = 2,
        title = "Инструменты",
        appsCount = 0,
        icon = 0,
        color = "0xFFAAD2D7",
        description = "Упрости свои рутинные задачи"
    ),
    CategoryInfo(
        id = 3,
        title = "Государственные",
        appsCount = 0,
        icon = 0,
        color = "0xFFEFE8A0",
        description = "Удобные сервисы для вас"
    ),
    CategoryInfo(
        id = 4,
        title = "Транспорт",
        appsCount = 0,
        icon = 0,
        color = "0xFFD7BFA3",
        description = "Всегда будь в движении"
    ),
    CategoryInfo(
        id = 5,
        title = "Игры",
        appsCount = 0,
        icon = 0,
        color = "0xFFA6D1EF",
        description = "Отвлекись от рутинных задач"
    )
)