package com.example.rustore_app_showcase.backend

import com.example.rustore_app_showcase.shared.AppInfo
import com.example.rustore_app_showcase.shared.CategoryInfo

private fun iconUrl(appId: Int) = "http://10.0.2.2:8080/icons/$appId"
private fun screenshots(appId: Int, count: Int) = List(count) { i -> "http://10.0.2.2:8080/screenshots/$appId/$i" }
private fun categoryIconUrl(categoryId: Int) = "http://10.0.2.2:8080/category-icons/$categoryId"
private fun apkUrl(appId: Int) = "http://10.0.2.2:8080/apk/$appId"

val allApps = listOf(
    AppInfo(
        id = 1,
        title = "СберБанк Онлайн",
        shortDescription = "Финансы и платежи",
        fullDescription = "Управляйте деньгами, оплачивайте счета и делайте переводы.",
        category = "Финансы",
        rating = 4.8,
        ratingCount = 5000,
        ratingPlace = 1,
        ageRating = 6,
        developerName = "Sberbank",
        iconUrl = iconUrl(1),
        screenshots = screenshots(1, 3),
        isInstalled = false,
        size = "210 МБ",
        lastVersion = "15.1",
        lastVersionDescription = "Новый дизайн",
        apkUrl = apkUrl(1)
    ),
    AppInfo(
        id = 2,
        title = "Т-Банк",
        shortDescription = "Банк №1",
        fullDescription = "Лучший мобильный банк с кэшбэком и инвестициями.",
        category = "Финансы",
        rating = 4.9,
        ratingCount = 4200,
        ratingPlace = 2,
        ageRating = 6,
        developerName = "T-Bank",
        iconUrl = iconUrl(2),
        screenshots = screenshots(2, 2),
        isInstalled = false,
        size = "190 МБ",
        lastVersion = "6.12",
        lastVersionDescription = "Улучшена стабильность",
        apkUrl = apkUrl(2)
    ),
    AppInfo(
        id = 3,
        title = "ВТБ Онлайн",
        shortDescription = "Цифровой банк",
        fullDescription = "Все банковские услуги в вашем смартфоне.",
        category = "Финансы",
        rating = 4.7,
        ratingCount = 3100,
        ratingPlace = 3,
        ageRating = 6,
        developerName = "VTB",
        iconUrl = iconUrl(3),
        screenshots = screenshots(3, 2),
        isInstalled = false,
        size = "180 МБ",
        lastVersion = "14.0",
        lastVersionDescription = "Обновление безопасности",
        apkUrl = apkUrl(3)
    ),
    AppInfo(
        id = 4,
        title = "Яндекс Старт",
        shortDescription = "Поиск и погода",
        fullDescription = "Все, что нужно для интернета, в одном приложении.",
        category = "Инструменты",
        rating = 4.6,
        ratingCount = 8000,
        ratingPlace = 1,
        ageRating = 0,
        developerName = "Yandex",
        iconUrl = iconUrl(4),
        screenshots = screenshots(4, 3),
        isInstalled = false,
        size = "95 МБ",
        lastVersion = "24.1",
        lastVersionDescription = "Умный поиск",
        apkUrl = apkUrl(4)
    ),
    AppInfo(
        id = 5,
        title = "Почта Mail.ru",
        shortDescription = "Быстрая почта",
        fullDescription = "Удобный почтовый клиент для всех ваших ящиков.",
        category = "Инструменты",
        rating = 4.5,
        ratingCount = 6500,
        ratingPlace = 2,
        ageRating = 0,
        developerName = "VK",
        iconUrl = iconUrl(5),
        screenshots = screenshots(5, 2),
        isInstalled = false,
        size = "70 МБ",
        lastVersion = "12.5",
        lastVersionDescription = "Тёмная тема",
        apkUrl = apkUrl(5)
    ),
    AppInfo(
        id = 6,
        title = "Госуслуги",
        shortDescription = "Гос. сервисы",
        fullDescription = "Запись к врачу, штрафы и документы в одном месте.",
        category = "Государство",
        rating = 4.6,
        ratingCount = 9000,
        ratingPlace = 1,
        ageRating = 0,
        developerName = "Минцифры РФ",
        iconUrl = iconUrl(6),
        screenshots = screenshots(6, 3),
        isInstalled = false,
        size = "88 МБ",
        lastVersion = "5.0",
        lastVersionDescription = "Новые уведомления",
        apkUrl = apkUrl(6)
    ),
    AppInfo(
        id = 7,
        title = "Мой налог",
        shortDescription = "Для самозанятых",
        fullDescription = "Официальное приложение ФНС России.",
        category = "Государство",
        rating = 4.8,
        ratingCount = 2000,
        ratingPlace = 2,
        ageRating = 0,
        developerName = "ФНС России",
        iconUrl = iconUrl(7),
        screenshots = screenshots(7, 2),
        isInstalled = false,
        size = "45 МБ",
        lastVersion = "2.3",
        lastVersionDescription = "Чеки по QR",
        apkUrl = apkUrl(7)
    ),
    AppInfo(
        id = 8,
        title = "Яндекс Go",
        shortDescription = "Такси и еда",
        fullDescription = "Быстрый заказ такси и доставка продуктов.",
        category = "Транспорт",
        rating = 4.9,
        ratingCount = 15000,
        ratingPlace = 1,
        ageRating = 4,
        developerName = "Yandex",
        iconUrl = iconUrl(8),
        screenshots = screenshots(8, 3),
        isInstalled = false,
        size = "115 МБ",
        lastVersion = "4.90",
        lastVersionDescription = "Улучшена навигация",
        apkUrl = apkUrl(8)
    ),
    AppInfo(
        id = 9,
        title = "2ГИС",
        shortDescription = "Карты и справочник",
        fullDescription = "Подробные карты городов даже без интернета.",
        category = "Транспорт",
        rating = 4.8,
        ratingCount = 12000,
        ratingPlace = 2,
        ageRating = 4,
        developerName = "2GIS",
        iconUrl = iconUrl(9),
        screenshots = screenshots(9, 2),
        isInstalled = false,
        size = "155 МБ",
        lastVersion = "11.2",
        lastVersionDescription = "Схемы этажей",
        apkUrl = apkUrl(9)
    ),
    AppInfo(
        id = 10,
        title = "Яндекс Карты",
        shortDescription = "Навигатор",
        fullDescription = "Транспорт онлайн и лучшие маршруты.",
        category = "Транспорт",
        rating = 4.8,
        ratingCount = 14000,
        ratingPlace = 3,
        ageRating = 4,
        developerName = "Yandex",
        iconUrl = iconUrl(10),
        screenshots = screenshots(10, 2),
        isInstalled = false,
        size = "140 МБ",
        lastVersion = "12.0",
        lastVersionDescription = "3D-здания",
        apkUrl = apkUrl(10)
    ),
    AppInfo(
        id = 11,
        title = "Мир Танков",
        shortDescription = "Легендарные бои",
        fullDescription = "Масштабные танковые сражения онлайн.",
        category = "Игры",
        rating = 4.5,
        ratingCount = 50000,
        ratingPlace = 1,
        ageRating = 12,
        developerName = "Lesta Games",
        iconUrl = iconUrl(11),
        screenshots = screenshots(11, 3),
        isInstalled = false,
        size = "2.5 ГБ",
        lastVersion = "1.24",
        lastVersionDescription = "Новый сезон",
        apkUrl = apkUrl(11)
    ),
    AppInfo(
        id = 12,
        title = "Rush Royale",
        shortDescription = "Tower Defense",
        fullDescription = "Сражайся в PvP и защищай свой замок.",
        category = "Игры",
        rating = 4.6,
        ratingCount = 30000,
        ratingPlace = 2,
        ageRating = 12,
        developerName = "MY.GAMES",
        iconUrl = iconUrl(12),
        screenshots = screenshots(12, 2),
        isInstalled = false,
        size = "600 МБ",
        lastVersion = "23.0",
        lastVersionDescription = "Новые герои",
        apkUrl = apkUrl(12)
    )
)

val allCategories = listOf(
    CategoryInfo(
        id = 1,
        title = "Финансы",
        appsCount = 0,
        icon = 0,
        color = "0xFFD1F6D3",
        description = "Полный контроль ваших финансов",
        iconUrl = categoryIconUrl(1)
    ),
    CategoryInfo(
        id = 2,
        title = "Инструменты",
        appsCount = 0,
        icon = 0,
        color = "0xFFAAD2D7",
        description = "Упрости свои рутинные задачи",
        iconUrl = categoryIconUrl(2)
    ),
    CategoryInfo(
        id = 3,
        title = "Государство",
        appsCount = 0,
        icon = 0,
        color = "0xFFEFE8A0",
        description = "Удобные сервисы для вас",
        iconUrl = categoryIconUrl(3)
    ),
    CategoryInfo(
        id = 4,
        title = "Транспорт",
        appsCount = 0,
        icon = 0,
        color = "0xFFD7BFA3",
        description = "Всегда будь в движении",
        iconUrl = categoryIconUrl(4)
    ),
    CategoryInfo(
        id = 5,
        title = "Игры",
        appsCount = 0,
        icon = 0,
        color = "0xFFA6D1EF",
        description = "Отвлекись от рутинных задач",
        iconUrl = categoryIconUrl(5)
    )
)
